quarkus.http.port= 8081
quarkus.swagger-ui.always-include=true
#Nota: Por defecto, Quarkus incluye esta interfaz Swagger UI solo en el modo Dev.
#Si deseas tenerla también en producción, puedes agregar la propiedad de configuración